name: extension
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: |
          jq .version=\"$(git describe)\" manifest.json > manifest.json.new
          mv manifest.json.new manifest.json
      - run: npx web-ext sign --api-key=${{secrets.AMO_JWT_ISSUER}} --api-secret=${{secrets.AMO_JWT_SECRET}}
      - uses: actions/upload-artifact@v3
        with:
          path: web-ext-artifacts/
